import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { QueryProvider } from "@/providers/query-provider";
import { Toaster } from "sonner";
import { SessionProvider } from "next-auth/react"
import { ThemeProvider } from "@/providers/theme-provider";
import { ModalProvider } from "@/providers/modal-provider";
import NextTopLoader from 'nextjs-toploader';
import { FcmProvider } from "@/providers/fcm-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
            <QueryProvider>
              <ThemeProvider
                attribute="class"
                defaultTheme="dark"
                disableTransitionOnChange
              >
                {children}
                <Toaster />
                <NextTopLoader showSpinner={false} />
                <ModalProvider />
              </ThemeProvider>
            </QueryProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
